### PR TITLE
update reva

### PR DESCRIPTION
**Pull request by butonic**
We changed the default configuration to integrate better with ocis.

- We use ocis-glauth as the default ldap server on port 9125 with base `dc=example,dc=org`.
- We use a dedicated technical `reva` user to make ldap binds
- Clients are supposed to use the ocis-proxy endpoint `https://localhost:9200`
- We removed unneeded ocis configuration from the frontend which no longer serves an oidc provider.
- We changed the default user OpaqueID attribute from `sub` to `preferred_username`. The latter is a claim populated by konnectd that can also be used by the reva ldap user manager to look up users by their OpaqueId

Bugfix: we fixed a typo in the `REVA_LDAP_SCHEMA_MAIL` environment variable.

It was misspelled as `REVA_LDAP_SCHEMA_Mail`.

requires https://github.com/owncloud/ocis-glauth/pull/9 and https://github.com/owncloud/ocis-konnectd/pull/52
- [x] TODO fix testing.md, see `.drone.star`

### CODE REVIEW

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ pkg/flagset/frontend.go  -1
+ pkg/flagset/authbearer.go  -1
+ pkg/flagset/authbasic.go  -1
+ pkg/flagset/users.go  -1
+ pkg/flagset/storageoc.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=5197118&bid=17044201)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ pkg/flagset/frontend.go  -1
+ pkg/flagset/storageoc.go  -1
+ pkg/flagset/users.go  -1
+ pkg/flagset/authbearer.go  -1
+ pkg/flagset/authbasic.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=5197118&bid=17044201)

**Comment by refs** [comment]
Acceptance tests are off

**Comment by butonic** [comment]
I think because the root storage is no longer used ... will dig into it

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- pkg/flagset/storageoc.go  3
- pkg/command/storageoc.go  1
- pkg/flagset/storageocdata.go  3
- pkg/flagset/storageroot.go  3
- pkg/flagset/storagehomedata.go  3
- pkg/flagset/storagehome.go  4
         

Clones removed
==============
+ pkg/flagset/authbasic.go  -1
+ pkg/command/storagehome.go  -1
+ pkg/flagset/users.go  -1
+ pkg/flagset/frontend.go  -1
+ pkg/flagset/authbearer.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=5197118&bid=17044201)

**Comment by butonic** [comment]
the path wrapping changed and trying to update the configs causes the acceptance tests to fail. I had to [submit an upstream change to the owncloud storage driver](https://github.com/cs3org/reva/pull/571) to fix the general problem, but some tests are still off.

**Comment by butonic** [comment]
hmmm
```
242 scenarios (5 passed, 237 failed)
--
2653 | 1715 steps (134 passed, 237 failed, 1344 skipped)
```

vs locally 

```
219 scenarios (181 passed, 38 failed)
1554 steps (1466 passed, 38 failed, 50 skipped)
```

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- pkg/flagset/storagehomedata.go  3
- pkg/flagset/storageroot.go  3
- pkg/flagset/storageoc.go  3
- pkg/flagset/storageocdata.go  3
- pkg/command/storageoc.go  1
- pkg/flagset/storagehome.go  4
         

Clones removed
==============
+ pkg/flagset/authbearer.go  -1
+ pkg/flagset/frontend.go  -1
+ pkg/command/storagehome.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=5197118&bid=17044201)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- pkg/command/storageoc.go  1
- pkg/flagset/storagehome.go  4
- pkg/flagset/storageroot.go  3
- pkg/flagset/storagehomedata.go  3
- pkg/flagset/storageocdata.go  3
- pkg/flagset/storageoc.go  3
         

Clones removed
==============
+ pkg/flagset/frontend.go  -1
+ pkg/command/storagehome.go  -1
+ pkg/flagset/authbearer.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=5197118&bid=17044201)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- pkg/flagset/storageroot.go  3
- pkg/flagset/storageocdata.go  3
- pkg/flagset/storagehome.go  4
- pkg/flagset/storagehomedata.go  3
- pkg/command/storageoc.go  1
- pkg/flagset/storageoc.go  3
         

Clones removed
==============
+ pkg/command/storagehome.go  -1
+ pkg/flagset/frontend.go  -1
+ pkg/flagset/authbearer.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=5197118&bid=17044201)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- pkg/flagset/storageocdata.go  3
- pkg/flagset/storagehome.go  4
- pkg/flagset/storageroot.go  3
- pkg/command/storageoc.go  1
- pkg/flagset/storageoc.go  3
- pkg/flagset/storagehomedata.go  3
         

Clones removed
==============
+ pkg/command/storagehome.go  -1
+ pkg/flagset/authbearer.go  -1
+ pkg/flagset/frontend.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=5197118&bid=17044201)

**Comment by butonic** [comment]
@individual-it with https://github.com/owncloud/core/pull/37149 the acceptance tests pass locally ... what is the process? change the core branch in the `.drone.star` to `ocis-tests-expect-40x-on-not-exist`, which should make this PR green, then merge core, then update this PR and revert to the core branch to master, wait for green light, merge?

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- pkg/flagset/storageoc.go  3
- pkg/flagset/storageroot.go  3
- pkg/command/storageoc.go  1
- pkg/flagset/storagehomedata.go  3
- pkg/flagset/storageocdata.go  3
- pkg/flagset/storagehome.go  4
         

Clones removed
==============
+ pkg/flagset/frontend.go  -1
+ pkg/command/storagehome.go  -1
+ pkg/flagset/authbearer.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=5197118&bid=17044201)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- pkg/flagset/storageocdata.go  3
- pkg/flagset/storageoc.go  3
- pkg/flagset/storageroot.go  3
- pkg/command/storageoc.go  1
- pkg/flagset/storagehome.go  4
- pkg/flagset/storagehomedata.go  3
         

Clones removed
==============
+ pkg/flagset/frontend.go  -1
+ pkg/flagset/authbearer.go  -1
+ pkg/command/storagehome.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=5197118&bid=17044201)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- pkg/command/storageoc.go  1
- pkg/flagset/storagehome.go  4
- pkg/flagset/storageroot.go  3
- pkg/flagset/storageocdata.go  3
- pkg/flagset/storageoc.go  3
- pkg/flagset/storagehomedata.go  3
         

Clones removed
==============
+ pkg/flagset/authbearer.go  -1
+ pkg/command/storagehome.go  -1
+ pkg/flagset/frontend.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=5197118&bid=17044201)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- pkg/flagset/storagehomedata.go  3
- pkg/flagset/storageocdata.go  3
- pkg/flagset/storagehome.go  4
- pkg/flagset/storageoc.go  3
- pkg/flagset/storageroot.go  3
- pkg/command/storageoc.go  1
         

Clones removed
==============
+ pkg/flagset/authbearer.go  -1
+ pkg/command/storagehome.go  -1
+ pkg/flagset/frontend.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=5197118&bid=17044201)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- pkg/flagset/storageocdata.go  3
- pkg/flagset/storageoc.go  3
- pkg/flagset/storagehome.go  4
- pkg/flagset/storagehomedata.go  3
- pkg/flagset/storageroot.go  3
- pkg/command/storageoc.go  1
         

Clones removed
==============
+ pkg/command/storagehome.go  -1
+ pkg/flagset/authbearer.go  -1
+ pkg/flagset/frontend.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=5197118&bid=17044201)

**Pull request merged**
