### PR TITLE
[Tests-Only] Bump core commit for API tests

### PR DESCRIPTION
**Pull request by phil-davis**
To match up with approximately core release 10.5.0.
So  we will be running the current relevant API acceptance tests.

### CODE REVIEW

**Comment by PVince81** [comment]
Idea: have a daily drone run that goes to OC core and does a `git log $currentCommitIdInDrone..master tests/acceptance/features/` (ideally limited to API tests) and then submits a PR to update said commit.

Or at least create a local script that one can run to do the update.
In case there are no test changes, return an error / don't submit a PR.

**Comment by phil-davis** [comment]
Rebased to get up-to-date CI

**Comment by PVince81** [comment]
huh, what it was green, why is CI running again now ??

**Comment by phil-davis** [comment]
It said "branch is out-of-date" so I guessed that this repo is setup to force you to have a fully-rebased branch before letting you merge.

**Comment by phil-davis** [comment]
> Idea: have a daily drone run that goes to OC core and does a `git log $currentCommitIdInDrone..master tests/acceptance/features/` (ideally limited to API tests) and then submits a PR to update said commit.
> 
> Or at least create a local script that one can run to do the update.
> In case there are no test changes, return an error / don't submit a PR.

Yes, we want the pinned commit from core for the test infrastructure and scenarios so that we don't get nasty surprises in core that suddenly break ocis CI. But we also want to know the result of running the latest core API tests, and update the pinned commit if CI is green.

Some magic in `ocis-reva` and `ocis` will be useful for the long-term.

**Pull request merged**
