### PR TITLE
Prepare release 0.14.0

### PR DESCRIPTION
**Pull request by PVince81**
- [ ] BLOCKED by https://github.com/owncloud/ocis-reva/issues/471 causing random test failures

### CODE REVIEW

**Comment by PVince81** [comment]
we can merge anyway, after that there will be yet another changelog generation

**Review by phil-davis — APPROVED** [review]

**Comment by PVince81** [comment]
Huh, weird... now the four tests I excluded in the other PR are passing...

**Comment by PVince81** [comment]
I've rebased again and removed the 4 expected failures... I hope these are not random :see_no_evil:

**Comment by phil-davis** [comment]
They are random. An example "fail" from a past run is:
```
     item "//d:response[2]/d:href" found with value "/remote.php/webdav/upload/file2.txt", expected to match regex pattern: "/remote\.php\/webdav\/upload\/file1.txt/"
        Failed asserting that '/remote.php/webdav/upload/file2.txt' matches PCRE pattern "/remote\.php\/webdav\/upload\/file1.txt/".
```

I think this issue: https://github.com/owncloud/ocis-reva/issues/471

```
    When user "Alice" gets the properties of folder "<folder_name>" with depth 1 using the WebDAV API                                           # WebDavPropertiesContext::userGetsThePropertiesOfFolderWithDepth()
    Then the value of the item "//d:response[1]/d:href" in the response to user "Alice" should match "/remote\.php\/<expected_href>\//"         # WebDavPropertiesContext::assertValueOfItemInResponseToUserRegExp()
    And the value of the item "//d:response[2]/d:href" in the response to user "Alice" should match "/remote\.php\/<expected_href>\/file1.txt/" # WebDavPropertiesContext::assertValueOfItemInResponseToUserRegExp()
    And the value of the item "//d:response[3]/d:href" in the response to user "Alice" should match "/remote\.php\/<expected_href>\/file2.txt/" # WebDavPropertiesContext::assertValueOfItemInResponseToUserRegExp()
```

The test steps assume a particular order of the folder and files in the PROPFIND response. That order is consistent in oC10 and with the OCIS "oc" storage. But this new OCIS "ocis" storage seems to send a more "random" order of files in the PROPFIND response.

The different order probably is acceptable - I doubt that the PROPFIND spec requires a particular sorted order of entries in the response.

So we need to make the test code more flexible.

How quickly to we need to do that!?

**Comment by PVince81** [comment]
I heard that Golang was shuffling the order of hash maps when iterating, this might explain the random order.

@butonic should we sort the properties before returning ? or use another container ?

**Comment by PVince81** [comment]
> How quickly to we need to do that!?

No rush, but would be good to have this beginning of next week so we can tag "ocis".

The tests are green now but I'm unsure whether we should merge in this state...

**Comment by PVince81** [comment]
@phil-davis the tests seem to be a bit too low level.

Instead of "Then the value of the item "//d:response[1]/d:href"" would likely better to say something like "there is an entry with href XYI in the response"

**Comment by phil-davis** [comment]
We already merged in `owncloud/ocis-reva` `master` after a pass. And I am quite sure that when people create other PRs on `master`  they will already sometimes get a pass and sometimes a fail. So merging this release branch will not make that any better or worse.

But yes, we should not pull this into `owncloud/ocis` and merge it until the test flexibility is sorted out.

**Comment by PVince81** [comment]
converted to draft

as I understand, the test in question is just doing a PROPFIND, we certainly have better ways to check whether a folder contents ??

**Comment by phil-davis** [comment]
Test is improved in core PR https://github.com/owncloud/core/pull/37902
Once that is confirmed and merged, I  can update the core commit here so that CI uses the improved (more flexible) test.

**Comment by phil-davis** [comment]
I have bumped the core commit id to get the new more-reliable core tests.
I will restart CI a couple of times to get confidence. Then this can be merged.

**Pull request merged**
