### PR TITLE
Update reva to v0.1.1-0.20200520150229

### PR DESCRIPTION
**Pull request by PVince81**

### CODE REVIEW

**Comment by PVince81** [comment]
20 failures

**Comment by C0rby** [comment]
This should fix some tests. https://github.com/owncloud/core/pull/37396

**Comment by PVince81** [comment]
let me temporarily point this PR at the core one to confirm

**Comment by PVince81** [comment]
- [ ] merge https://github.com/owncloud/core/pull/37396
- [ ] revert drone branch pointer to master

**Comment by PVince81** [comment]
hmmm, strange. API tests still fail with sharing: https://cloud.drone.io/owncloud/ocis-reva/371/2/6

@C0rby

**Comment by C0rby** [comment]
Ok let me check locally.

**Comment by C0rby** [comment]
That's strange. Locally I get these errors.
```
Failed scenarios:

    /home/corby/Development/oc_repos/core/tests/acceptance/features/apiMain/checksums.feature:255
    /home/corby/Development/oc_repos/core/tests/acceptance/features/apiMain/checksums.feature:256
    /home/corby/Development/oc_repos/core/tests/acceptance/features/apiWebdavMove2/moveFile.feature:21
    /home/corby/Development/oc_repos/core/tests/acceptance/features/apiWebdavMove2/moveFile.feature:22
    /home/corby/Development/oc_repos/core/tests/acceptance/features/apiWebdavOperations/deleteFolderContents.feature:31
    /home/corby/Development/oc_repos/core/tests/acceptance/features/apiWebdavOperations/deleteFolderContents.feature:32
    /home/corby/Development/oc_repos/core/tests/acceptance/features/apiWebdavOperations/downloadFile.feature:40
    /home/corby/Development/oc_repos/core/tests/acceptance/features/apiWebdavOperations/downloadFile.feature:41
```

**Comment by PVince81** [comment]
let's investigate in detail next week as I'd like to focus on releases today

**Comment by PVince81** [comment]
I'll release without this update in https://github.com/owncloud/ocis-reva/pull/215.

Still, will rebase that branch to see if CI is still running propertly in case some new test issues have sneaked in somehow

**Comment by PVince81** [comment]
something is fishy... I tried one of the tests "tests/acceptance/features/apiWebdavOperations/downloadFile.feature:40" and it also fails on https://github.com/owncloud/ocis-reva/pull/215 where it passed before.

**Comment by C0rby** [comment]
I think there have been some changes to the tests. I see that the test user is now "Alice" and not "user0".

**Comment by phil-davis** [comment]
> I think there have been some changes to the tests. I see that the test user is now "Alice" and not "user0".

In core the acceptance test features were change to use "realistic" user names. In theory there should be no problem! I suspect that the most likely problem might be if a system-under-test behaves differently to ownCloud10 when the username is mixed-case.

**Comment by PVince81** [comment]
I tried reverting to the commit before the name changes, but the test still fails

**Comment by PVince81** [comment]
In my local log I saw errors about invalid Depth header values that were used in the tests.

Since https://github.com/cs3org/reva/pull/758 those values are forbidden.

I'll have a look and fix all the tests that use an invalid depth value to use infinity instead

**Comment by PVince81** [comment]
Confirmed: when I sit on the commit before the Depth validation, the test passes.

**Comment by PVince81** [comment]
PR here to fix invalid depth values and pre-validate: https://github.com/owncloud/core/pull/37437

**Comment by PVince81** [comment]
and adjusted the drone config to test against that PR

**Comment by PVince81** [comment]
failures now:
```
/srv/app/testrunner/tests/acceptance/features/apiAuthOcs/ocsGETAuth.feature:99
/srv/app/testrunner/tests/acceptance/features/apiShareCreateSpecial2/createShareWithInvalidPermissions.feature:64
/srv/app/testrunner/tests/acceptance/features/apiShareCreateSpecial2/createShareWithInvalidPermissions.feature:101
/srv/app/testrunner/tests/acceptance/features/apiShareCreateSpecial2/createShareWithInvalidPermissions.feature:103
/srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:92
/srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:95
/srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:98
/srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:101
/srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:131
/srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:240
```

at least no more checksum, etc.

next up: to test with https://github.com/owncloud/core/pull/37396 as well

**Comment by PVince81** [comment]
pushed again using the core branch "tests-valid-depth-and-shares-update" which contains both the Depth fixes and the sharing ones

**Comment by PVince81** [comment]
ok, so once we merge both https://github.com/owncloud/core/pull/37396 and https://github.com/owncloud/core/pull/37437 there are still remaining failures:
```
    /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:56
    /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:57
    /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:59
    /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:60
    /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:62
    /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:63
    /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:65
    /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:66
```

there likely for @C0rby to check ^

**Comment by dpakach** [comment]
@PVince81 phoenix ui tests have passed in https://github.com/owncloud/ocis-reva/pull/223, please review and rebase on that

**Comment by PVince81** [comment]
I've merged https://github.com/owncloud/ocis-reva/pull/223 but will rebase later once at least https://github.com/owncloud/core/pull/37396 is merged.

for the remaining failing API tests from https://github.com/owncloud/ocis-reva/pull/221#issuecomment-632619198 we can either debug them or skip them

**Comment by C0rby** [comment]
> ok, so once we merge both [owncloud/core#37396](https://github.com/owncloud/core/pull/37396) and [owncloud/core#37437](https://github.com/owncloud/core/pull/37437) there are still remaining failures:
> 
> ```
>     /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:56
>     /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:57
>     /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:59
>     /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:60
>     /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:62
>     /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:63
>     /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:65
>     /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:66
> ```
> 
> there likely for @C0rby to check ^

I can't reproduce that locally. They are running green on my machine....

**Comment by PVince81** [comment]
ok https://github.com/owncloud/core/pull/37437 is merged.

@C0rby can you rebase https://github.com/owncloud/core/pull/37396 ?

**Comment by PVince81** [comment]
I've rebased this PR, and pointed it again at https://github.com/owncloud/core/pull/37396

**Comment by C0rby** [comment]
> ok [owncloud/core#37437](https://github.com/owncloud/core/pull/37437) is merged.
> 
> @C0rby can you rebase [owncloud/core#37396](https://github.com/owncloud/core/pull/37396) ?

Done

**Comment by PVince81** [comment]
I've restarted the build now, we should get results. I suspect we will only see those createShare issues. We'll see.

**Comment by PVince81** [comment]
No more Phoenix failures.
Remaining failures as before on the mixed branch:
```
     /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:56
     /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:57
     /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:59
     /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:60
     /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:62
     /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:63
     /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:65
     /srv/app/testrunner/tests/acceptance/features/apiShareManagementBasic/createShare.feature:66
```

**Comment by PVince81** [comment]
those tests pass locally for me as well... hmmm

**Comment by PVince81** [comment]
ok got it, it's the "missing mimetype value" again.

see https://github.com/owncloud/ocis-reva/issues/67#issuecomment-623947583

I think we should fix the Drone env to actually have a proper /etc/mime.types folder.
Might need to apt-get some extra package on those images ?

@individual-it @dpakach

**Comment by PVince81** [comment]
I believe the dockers are based on Alpine, so it should be a matter of installing "mailcap", see https://pkgs.alpinelinux.org/contents?file=mime.types&path=&name=mailcap&branch=edge&repo=main&arch=armhf

**Comment by PVince81** [comment]
naive attempt in this separate PR to add mime.types file in Drone: https://github.com/owncloud/ocis-reva/pull/224

**Comment by PVince81** [comment]
@C0rby can you undraft https://github.com/owncloud/core/pull/37396 and I hope @individual-it can review/approve it, then we should merge both at the same time

**Comment by PVince81** [comment]
right, not merging at the same time. here is the correct plan:
- [ ] undraft https://github.com/owncloud/core/pull/37396 and get approval
- [ ] merge https://github.com/owncloud/core/pull/37396
- [ ] adjust this PR here (https://github.com/owncloud/ocis-reva/pull/221) to point again at master and wait for CI
- [ ] merge this PR

**Comment by PVince81** [comment]
rebased and made the branch point back to core master.

**Pull request merged**
