### PR TITLE
Test to prove that 67 works

### PR DESCRIPTION
**Pull request by PVince81**
To demonstrate and debug https://github.com/owncloud/ocis-reva/issues/67

Matches core PR https://github.com/owncloud/core/pull/37344

### CODE REVIEW

**Comment by individual-it** [comment]
same issue I fear
image

**Comment by PVince81** [comment]
next up ideas to try:
- [ ] running drone locally with that test
- [ ] bringing local env as close as possible to the one from Drone

**Comment by PVince81** [comment]
differences in env compared to https://owncloud.github.io/extensions/ocis_reva/testing :
- on Drone, we're missing:
   - REVA_USERS_DRIVER=ldap
   - REVA_LDAP_USERFILTER
   - REVA_LDAP_GROUPFILTER
   - REVA_LDAP_SCHEMA_UID
   - REVA_LDAP_SCHEMA_MAIL
   - REVA_LDAP_SCHEMA_CN
- in the documentation, some env vars are not set that do exist on CI, probably we are relying on defaults:
   - `'REVA_STORAGE_HOME_DATA_TEMP_FOLDER': '/srv/app/tmp/',`
   - `'REVA_STORAGE_OWNCLOUD_DATADIR': '/srv/app/tmp/reva/data',`
   - `'REVA_STORAGE_OC_DATA_TEMP_FOLDER': '/srv/app/tmp/',`
   - `'REVA_STORAGE_OWNCLOUD_REDIS_ADDR': 'redis:6379',`
   - `'REVA_SHARING_USER_JSON_FILE': '/srv/app/tmp/reva/shares.json'`
- the list of started reva services is identical

so far I don't see why this would make a difference

**Comment by PVince81** [comment]
I've modified the config now to only run that one issue for quicker results.

**Comment by PVince81** [comment]
likely an env issue, maybe "/etc/mime.types" is minimal or does not exist: https://golang.org/pkg/mime/#TypeByExtension

see https://github.com/owncloud/ocis-reva/issues/67#issuecomment-623947583 for context

still, I think it might make sense to add an additional test to read the mime type of a text file from Webdav, it will likely highlight this env issue further even after the reva fix @individual-it

**Comment by PVince81** [comment]
added commit to print out mime types file, we'll see

**Comment by PVince81** [comment]
hah...
```
cat: can't open '/etc/mime.types': No such file or directory
```

so this is the explanation why it failed on Drone but passed locally, as we locally have that file @individual-it ^

**Comment by PVince81** [comment]
rebased so it runs with the actual fixes

**Comment by PVince81** [comment]
rebased again for further changes

the build setup failed anyway

**Comment by PVince81** [comment]
some weird shit happening here:
```

=== RUN   TestRegisterGRPCEndpoint
--

```

anyway, the code PR was merged already.
if by any bad luck the size issue is still there on master, let me know...

**Pull request closed without merging**
