### PR TITLE
update reva to v0.0.2-0.20200212114015-0dbce24f7e8b

### PR DESCRIPTION
**Pull request by butonic**
- reva configuration changed a bit,
  - [x] adjust config for shared jwt token
  - [x] add new config options
    - [x] layout
    - [ ] ~~others?~~
- [x] login work
- [x] file upload is broken
- [x] the root storage may no longer be necessary
  - [ ] only affects ocis
- [x] update docs
- [x] add changelog
- [x] uses grpc-go (v1.27.0), so we will run into the same problem as https://github.com/etcd-io/etcd/issues/11563
  - maybe it will get fixed in etcd by the time we try to use this in ocis: https://github.com/etcd-io/etcd/pull/11564
  - can be worked around by putting `replace google.golang.org/grpc => google.golang.org/grpc v1.26.0` into ocis go.mod

### CODE REVIEW

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- pkg/flagset/storageoc.go  1
- pkg/flagset/storageroot.go  1
         

Clones removed
==============
+ pkg/command/sharing.go  -1
+ pkg/command/storagehome.go  -1
+ pkg/command/authbasic.go  -3
+ pkg/command/authbearer.go  -3
+ pkg/command/storageroot.go  -1
+ pkg/command/frontend.go  -2
+ pkg/command/storageoc.go  -2
+ pkg/command/gateway.go  -5
+ pkg/command/users.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=4995150&bid=16486439)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- pkg/flagset/storageoc.go  1
- pkg/flagset/storageroot.go  1
         

Clones removed
==============
+ pkg/command/sharing.go  -1
+ pkg/command/authbearer.go  -3
+ pkg/command/storageoc.go  -2
+ pkg/command/gateway.go  -5
+ pkg/command/frontend.go  -2
+ pkg/command/authbasic.go  -3
+ pkg/command/storagehome.go  -1
+ pkg/command/users.go  -2
+ pkg/command/storageroot.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=4995150&bid=16486439)

**Comment by C0rby** [comment]
File upload works without a problem.
To build it with ocis while the etcd issue is not resolved one has to put a replace in the go.mod file for reva and set the google.golang.org/grpc version to 1.26.0 in reva.

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- pkg/flagset/storageoc.go  1
- pkg/flagset/storageroot.go  1
         

Clones removed
==============
+ pkg/command/frontend.go  -2
+ pkg/command/authbearer.go  -3
+ pkg/command/storageoc.go  -2
+ pkg/command/storageroot.go  -1
+ pkg/command/authbasic.go  -3
+ pkg/command/storagehome.go  -1
+ pkg/command/users.go  -2
+ pkg/command/gateway.go  -5
+ pkg/command/sharing.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=4995150&bid=16486439)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- pkg/flagset/storageoc.go  1
- pkg/flagset/storageroot.go  1
         

Clones removed
==============
+ pkg/command/gateway.go  -5
+ pkg/command/authbasic.go  -3
+ pkg/command/storagehome.go  -1
+ pkg/command/storageroot.go  -1
+ pkg/command/frontend.go  -2
+ pkg/command/sharing.go  -1
+ pkg/command/users.go  -2
+ pkg/command/authbearer.go  -3
+ pkg/command/storageoc.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=4995150&bid=16486439)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- pkg/flagset/storageoc.go  1
- pkg/flagset/storageroot.go  1
         

Clones removed
==============
+ pkg/command/gateway.go  -5
+ pkg/command/authbasic.go  -3
+ pkg/command/sharing.go  -1
+ pkg/command/frontend.go  -2
+ pkg/command/storageoc.go  -2
+ pkg/command/authbearer.go  -3
+ pkg/command/storageroot.go  -1
+ pkg/command/storagehome.go  -1
+ pkg/command/users.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=4995150&bid=16486439)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- pkg/flagset/storageoc.go  1
- pkg/flagset/storageroot.go  1
         

Clones removed
==============
+ pkg/command/storagehome.go  -1
+ pkg/command/sharing.go  -1
+ pkg/command/users.go  -2
+ pkg/command/storageroot.go  -1
+ pkg/command/authbasic.go  -3
+ pkg/command/frontend.go  -2
+ pkg/command/gateway.go  -5
+ pkg/command/authbearer.go  -3
+ pkg/command/storageoc.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=4995150&bid=16486439)

**Pull request merged**
