### PR TITLE
Make global TUS capability configurable

### PR DESCRIPTION
**Pull request by PVince81**
Added global TUS capability in the config structure.
Added config switches for the advertised max chunk size and http method
override.

- [ ] adjust value semantics for tus_support and max_chunk_size (see original ticket)
- [x] add config switch to disable "tus_support" completely
- [x] add changelog entry

Requires https://github.com/cs3org/reva/pull/775 to work.

### CODE REVIEW

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/frontend.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=5586282&bid=18307301)

**Comment by PVince81** [comment]
- [ ] fix tus disable switch: somehow env var doesn't disable it: `export REVA_FRONTEND_UPLOAD_DISABLE_TUS=true`
- [ ] check if we should also disable the TUS implementation as reva might have switches for that already

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/frontend.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=5586282&bid=18307301)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/frontend.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=5586282&bid=18307301)

**Comment by refs** [comment]
@PVince81 merge or do you want to update reva dependency on the PR?

**Comment by PVince81** [comment]
@refs I usually prefer to update reva separately

**Comment by refs** [comment]
> @refs I usually prefer to update reva separately

good, let's keep it that way 👍

**Pull request merged**
