### PR TITLE
fix default port in documentation

### PR DESCRIPTION
**Pull request by individual-it**

### CODE REVIEW

**Comment by micbar** [comment]
@individual-it Could you push again?

**Comment by individual-it** [comment]
@micbar pushed again, but drone does not start somehow

**Comment by micbar** [comment]
@individual-it hook was offline, try again pls

**Comment by micbar** [comment]
@butonic @DeepDiver1975 @refs We are drifting a bit apart.

Ocis phoenix is using a StringSlice as a flag, not a comma separated list.
https://github.com/owncloud/ocis-reva/blob/master/pkg/flagset/authbasic.go#L215

I saw this because the staticcheck is complaining about the unused services list.

See https://github.com/owncloud/ocis-phoenix/pull/35#issue-367359113

Where are we defining out standards which we should follow across all extensions?

**Comment by refs** [comment]
sorry, I fixed that one yesterday before boarding the plane and didn't notify much on it. We're just following the way cli frameworks out there are doing it, which in my opinion is strange because it's not POSIX compliant:

As per the spec:

> When multiple option-arguments are specified to follow a single option, they should be presented as a single argument, using <comma> characters within that argument or <blank> characters within that argument to separate them.

[source](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html)

but for means of convention I'd like to stick to this way.

**Comment by C0rby** [comment]
So I will just refactor the config code here to make it consistent.

**Comment by micbar** [comment]
What? Merged with a red CI?

**Comment by individual-it** [comment]
restarted the build and it passed https://cloud.drone.io/owncloud/ocis-reva/9
this was just a change in the docu, but still I would prefer not to merge anything with red CI

**Comment by butonic** [comment]
hmmm ... I should not look at PRs when at a conference ... too distracted ... sorry

**Pull request merged**
