### PR TITLE
Change default settings to be able to run ocis server without any config

### PR DESCRIPTION
**Pull request by IljaN**
- Konnectd uses no TLS as it is behind the proxy.
- Glauth generates dev-certificates for ldap on startup if none is provided.
- Glauth can launch unencrypted (9125) and encrypted (9126) port in parallel

### CODE REVIEW

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- pkg/flagset/storagehome.go  4
- pkg/command/storageoc.go  1
- pkg/flagset/storageoc.go  3
- pkg/flagset/storageroot.go  3
- pkg/flagset/storagehomedata.go  3
- pkg/flagset/storageocdata.go  3
         

Clones removed
==============
+ pkg/command/storagehome.go  -1
+ pkg/flagset/users.go  -1
+ pkg/flagset/frontend.go  -1
+ pkg/flagset/authbasic.go  -1
+ pkg/flagset/authbearer.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=5205078&bid=17072137)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- pkg/flagset/storagehome.go  4
- pkg/command/storageoc.go  1
- pkg/flagset/storageocdata.go  3
- pkg/flagset/storageoc.go  3
- pkg/flagset/storageroot.go  3
- pkg/flagset/storagehomedata.go  3
         

Clones removed
==============
+ pkg/command/storagehome.go  -1
+ pkg/flagset/authbearer.go  -1
+ pkg/flagset/frontend.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=5205078&bid=17072137)

**Comment by micbar** [comment]
@IljaN @butonic Close this?

**Comment by IljaN** [comment]
Done

**Pull request closed without merging**
