### PR TITLE
Update reva to 20200624

### PR DESCRIPTION
**Pull request by PVince81**
To run CI, to avoid extra surprises...

### CODE REVIEW

**Comment by PVince81** [comment]
some failed scenarios: 
image

Content-Length header issue fix will need adjustments in the test expectation, can you prepare a PR @C0rby and confirm whether it fixes all these cases ?

**Comment by C0rby** [comment]
> some failed scenarios:
> image
> 
> Content-Length header issue fix will need adjustments in the test expectation, can you prepare a PR @C0rby and confirm whether it fixes all these cases ?

Yes, will do later.

**Comment by PVince81** [comment]
windows build failing?? https://cloud.drone.io/owncloud/ocis-reva/486/8/3 @micbar

**Comment by C0rby** [comment]
Here is the pr for the content-length tests https://github.com/owncloud/core/pull/37556

I need to open another pr because of the `ocs:share-permissions` ticket I implemented.

**Comment by C0rby** [comment]
So here is the other test change. https://github.com/owncloud/core/pull/37557

**Comment by phil-davis** [comment]
Note: when the core PRs have been merged to core master, then to get the effect of those in the testing here, you will need to edit `.drone.star` line 4:
```
apiTests(ctx, 'master', '158bd976047ea8abd137e2c61905d9dd63dc977d'),
```
This pins the test runner to a particular commit of core master (so that the API tests used from core do not keep changing "unexpectedly").

Replace `158bd976047ea8abd137e2c61905d9dd63dc977d` with the current latest commit in core master.

**Comment by C0rby** [comment]
So my test changes are merged.

**Comment by phil-davis** [comment]
I update `.drone.star` to use the current latest core master commit for the API  tests.

**Comment by phil-davis** [comment]
Latest API tests pass https://cloud.drone.io/owncloud/ocis-reva/490/2/6 - that's good.

Windows pipeline fails https://cloud.drone.io/owncloud/ocis-reva/490/8/3 - I have no idea about that.

**Comment by PVince81** [comment]
there will be more once we update to get the public link changes, there's a core PR for the many enabled tests: https://github.com/owncloud/core/pull/37552

**Comment by PVince81** [comment]
the Windows fail is likely related to the ocis-reva update. as I can see it did not fail on master for other PRs.

**Comment by PVince81** [comment]
updated the branch again and hoping for the Windows fail to go away, in case it was fixed recently

if not, I'll have a look... seems like stuff the linter missed in reva

**Comment by phil-davis** [comment]
https://cloud.drone.io/owncloud/ocis-reva/492/8/3
sadly Windows is still failing.

**Comment by PVince81** [comment]
this error doesn't make sense to me: why would duplicate symbols be allowed on a non-Windows build ?

**Comment by PVince81** [comment]
hmmm, if I understand correctly the compiler must likely ignore one of the files depending on what we compile. So the Linux build would not touch the Windows files so there would be no duplication.

also found this: https://github.com/golang/go/issues/29202#issuecomment-600220367

**Comment by PVince81** [comment]
as far as I understood, Golang automatically selects the file to compile based on the platform. So all files with "*_unix.go" would only be compiled on Unix and "*_windows.go" would only be compiled on Windows. However the error above sounds like it still touched the "_unix" files...
https://stackoverflow.com/a/25162021

**Comment by PVince81** [comment]
aha, this is likely the PR that introduced the issue: https://github.com/cs3org/reva/pull/833

**Comment by PVince81** [comment]
updated to get the build tags removal revert, let's see...

**Comment by PVince81** [comment]
it worked!

rebased and squashed now to get this mergable

**Comment by PVince81** [comment]
- [ ] we should also enable tests for https://github.com/owncloud/ocis-reva/issues/174

**Comment by phil-davis** [comment]
For a start, update the core commit id for the API tests in drone to the latest core master `e2b0a01a8807f549cbd1a42c7bd35f8cfc224ef7` - then it will be using the very latest core test scenarios.

**Comment by PVince81** [comment]
I have some local compilation issues in the "ocis" repo when I used this branch that updated reva, so before merging need to investigate to make sure we're not blocking other people with a broken state.

- [ ] investigate compilation issue in "ocis"

```
go build -v -tags '' -ldflags '-s -w -X "github.com/owncloud/ocis/pkg/version.String=284a999" -X "github.com/owncloud/ocis/pkg/version.Date=20200622"' -o bin/ocis ./cmd/ocis
github.com/cs3org/reva/pkg/eosclientgrpc/eos_grpc
# github.com/cs3org/reva/pkg/eosclientgrpc/eos_grpc
../../../../go/pkg/mod/github.com/cs3org/reva@v0.1.1-0.20200622084157-4925dc73ec86/pkg/eosclientgrpc/eos_grpc/eos_grpc.pb.go:4165:7: undefined: grpc.ClientConnInterface
../../../../go/pkg/mod/github.com/cs3org/reva@v0.1.1-0.20200622084157-4925dc73ec86/pkg/eosclientgrpc/eos_grpc/eos_grpc.pb.go:4169:11: undefined: grpc.SupportPackageIsVersion6
../../../../go/pkg/mod/github.com/cs3org/reva@v0.1.1-0.20200622084157-4925dc73ec86/pkg/eosclientgrpc/eos_grpc/eos_grpc.pb.go:4193:5: undefined: grpc.ClientConnInterface
../../../../go/pkg/mod/github.com/cs3org/reva@v0.1.1-0.20200622084157-4925dc73ec86/pkg/eosclientgrpc/eos_grpc/eos_grpc.pb.go:4196:22: undefined: grpc.ClientConnInterface
make: *** [Makefile:101: bin/ocis] Error 2
```

**Comment by PVince81** [comment]
Updated to reva from 20200624, should fix the compilation issues.

**Comment by PVince81** [comment]
API-tests passed but the Go tests seem to fail:
image

**Pull request merged**
