### PR TITLE
Point frontend to proxy

### PR DESCRIPTION
**Pull request by kulmann**
Changes based on https://github.com/owncloud/ocis-proxy/issues/44#issuecomment-638815447
Solving parts of https://github.com/owncloud/product/issues/72

You will need to adapt the proxy config like in the new example (add `/data` endpoint):
https://github.com/owncloud/ocis-proxy/pull/45

- [ ] adjust config
- [x] fix copy tests
- [x] check / enable public link tests
- [x] revert public link test commit
- [x] merge https://github.com/owncloud/core/pull/37552

### CODE REVIEW

**Comment by kulmann** [comment]
CI is green. We should wait until https://github.com/cs3org/reva/pull/878 is merged. Otherwise the new default config will break uploads.

**Comment by PVince81** [comment]
a lot of tests already failed: https://cloud.drone.io/owncloud/ocis-reva/511/2/6

why ?

**Comment by PVince81** [comment]
ah, probably need to first update ocis master to have the ocis-proxy + ocis-migration there ?

**Comment by kulmann** [comment]
@PVince81 we have updated reva again and explicitly set the URLs for datagateway and frontend, so that the tests can still run without ocis-proxy. Let's see what CI says.

**Comment by butonic** [comment]
manually testing ran into problms with the static binary again ... 
```
goroutine 44 [syscall]:
runtime.cgocall(0x1e7e480, 0xc002324bf0, 0xc000129c58)
        /usr/lib/go/src/runtime/cgocall.go:133 +0x5b fp=0xc002324bc0 sp=0xc002324b88 pc=0x4053ab
os/user._Cfunc_mygetpwnam_r(0xc001ea0e70, 0xc001ea6b70, 0x7fcf34000b60, 0x400, 0xc000129c58, 0x0)
        _cgo_gotypes.go:156 +0x4d fp=0xc002324bf0 sp=0xc002324bc0 pc=0x5c0bcd
os/user.lookupUser.func1.1(0xc001ea0e70, 0x9, 0x9, 0xc001ea6b70, 0xc001ea52d0, 0xc000129c58, 0xc002324ca0)
        /usr/lib/go/src/os/user/cgo_lookup_unix.go:70 +0xf3 fp=0xc002324c40 sp=0xc002324bf0 pc=0x5c2ab3
os/user.lookupUser.func1(0x251f640)
        /usr/lib/go/src/os/user/cgo_lookup_unix.go:70 +0x57 fp=0xc002324c88 sp=0xc002324c40 pc=0x5c2b37
os/user.retryWithBuffer(0xc001ea52d0, 0xc002324d70, 0x8, 0xc001ea0e70)
        /usr/lib/go/src/os/user/cgo_lookup_unix.go:247 +0x3b fp=0xc002324ce0 sp=0xc002324c88 pc=0x5c20ab
os/user.lookupUser(0xc0021d2a78, 0x8, 0x0, 0x0, 0x0)
        /usr/lib/go/src/os/user/cgo_lookup_unix.go:61 +0x1a1 fp=0xc002324dc8 sp=0xc002324ce0 pc=0x5c1161
os/user.Lookup(0xc0021d2a78, 0x8, 0xc00009fa40, 0x0, 0x0)
        /usr/lib/go/src/os/user/lookup.go:36 +0x70 fp=0xc002324e18 sp=0xc002324dc8 pc=0x5c0580
github.com/cs3org/reva/pkg/eosclient.(*Client).getUnixUser(...)
        /home/jfd/Repositories/reva/pkg/eosclient/eosclient.go:166
```
will test again with the new eos docker containers tomorrow

**Comment by PVince81** [comment]
Interesting, now much less tests fail but also I don't understand why the copy operation would fail:
image

**Comment by PVince81** [comment]
a 500 error:
```
 [1mScenario Outline:[22m Copying a file                                                                         [30m# /srv/app/testrunner/tests/acceptance/features/apiWebdavProperties1/copyFile.feature:15[39m
    [36mGiven using [39m[36;1m<dav_version>[39;22m[36m DAV path[39m                                                                     [30m# FeatureContext::usingOldOrNewDavPath()[39m
    [36mWhen user "[39m[36;1mAlice[39;22m[36m" copies file "[39m[36;1m/textfile0.txt[39;22m[36m" to "[39m[36;1m/FOLDER/textfile0.txt[39;22m[36m" using the WebDAV API[39m         [30m# FeatureContext::userCopiesFileUsingTheAPI()[39m
    [36mThen the HTTP status code should be "[39m[36;1m201[39;22m[36m"[39m                                                              [30m# FeatureContext::thenTheHTTPStatusCodeShouldBe()[39m
    [36mAnd the content of file "[39m[36;1m/FOLDER/textfile0.txt[39;22m[36m" for user "[39m[36;1mAlice[39;22m[36m" should be "[39m[36;1mownCloud test text file 0[39;22m[36m"[39m [30m# FeatureContext::contentOfFileForUserShouldBe()[39m

    [1mExamples:[22m
      |[36;1m dav_version [39;22m|
      |[32m old         [39m|
[31m        HTTP status code 500 is not the expected value 201
        Failed asserting that 500 matches expected '201'.[39m
      |[32m new         [39m|
[31m        HTTP status code 500 is not the expected value 201
        Failed asserting that 500 matches expected '201'.[39m
```

**Comment by PVince81** [comment]
I think the COPY operation is likely using a PUT (or TUS?) to reupload files to the backend / data gateway, that might be the place where it fails as it would also count like an upload.

**Comment by PVince81** [comment]
I've pushed a temp commit https://github.com/owncloud/ocis-reva/pull/261/commits/181cdef6bfbd525cffd08817c94bacfb91395be8 to use the tests from https://github.com/owncloud/core/pull/37552.
this will confirm that public links still work

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/flagset/storagedrivers.go  1
- pkg/flagset/common.go  1
         

Clones added
============
- pkg/flagset/common.go  2
- pkg/flagset/frontend.go  1
- pkg/flagset/gateway.go  2
         

Clones removed
==============
+ pkg/flagset/storageocdata.go  -17
+ pkg/flagset/storagepubliclink.go  -3
+ pkg/flagset/storageeosdata.go  -16
+ pkg/flagset/storagehomedata.go  -15
+ pkg/flagset/storageoc.go  -15
+ pkg/flagset/storagehome.go  -13
+ pkg/flagset/storageroot.go  -15
+ pkg/flagset/storageeos.go  -14
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=5686610&bid=18614047)

**Comment by PVince81** [comment]
public link tests fail: https://cloud.drone.io/owncloud/ocis-reva/516/2/6
but for me they pass locally, it might be because I'm testing through ocis.
will try running the tests on ocis-reva directly

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/flagset/storagedrivers.go  1
- pkg/flagset/common.go  1
         

Clones added
============
- pkg/flagset/gateway.go  2
- pkg/flagset/frontend.go  1
- pkg/flagset/common.go  2
         

Clones removed
==============
+ pkg/flagset/storageoc.go  -15
+ pkg/flagset/storageocdata.go  -17
+ pkg/flagset/storageeos.go  -14
+ pkg/flagset/storagehome.go  -13
+ pkg/flagset/storagehomedata.go  -15
+ pkg/flagset/storageeosdata.go  -16
+ pkg/flagset/storageroot.go  -15
+ pkg/flagset/storagepubliclink.go  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-reva/pullRequest?prid=5686610&bid=18614047)

**Comment by kulmann** [comment]
> I think the COPY operation is likely using a PUT (or TUS?) to reupload files to the backend / data gateway, that might be the place where it fails as it would also count like an upload.

That was the exact reason for failing webdav COPY. It download and then uploads (with TUS) internally and the reva transfer token was missing on both internal requests.

**Comment by PVince81** [comment]
seems the config changes have broken upload and other stuff https://github.com/owncloud/ocis-reva/pull/261/commits/35aea683016142ffc0743ec197883a6317e5f65e

I've reverted this now.

**Comment by PVince81** [comment]
ok, copy and upload issues are gone

next up, fix the public link issues (they were not visible originally as they were not enabled)

**Comment by PVince81** [comment]
seems the public link service was not started on Drone

**Pull request merged**
