### PR TITLE
Update reva to 20200701

### PR DESCRIPTION
**Pull request by PVince81**
For  https://github.com/owncloud/ocis-reva/issues/327

- [x] update again
- [x] fix for CI, https://github.com/owncloud/core/pull/37624
- [x] update CI commit to latest core master

### CODE REVIEW

**Comment by PVince81** [comment]
regression /srv/app/testrunner/tests/acceptance/features/apiShareUpdate/updateShare.feature:179 :'(

**Comment by phil-davis** [comment]
https://cloud.drone.io/cs3org/reva/1672/4/6

I am getting core acceptance tests running in cs3org/reva and just got exactly this fail:
```
  @skipOnOcV10
  Scenario: cannot get information of a specific share                                                     # /drone/src/tmp/testrunner/tests/acceptance/features/apiShareUpdate/updateShare.feature:179
    Given these users have been created with default attributes and without skeleton files:                # FeatureContext::theseUsersHaveBeenCreatedWithDefaultAttributesAndWithoutSkeletonFiles()
      | username |
      | Brian    |
      | Carol    |
    And user "Alice" has created folder "/Alice-folder"                                                    # FeatureContext::userHasCreatedFolder()
    And user "Alice" has created folder "/Alice-folder/folder2"                                            # FeatureContext::userHasCreatedFolder()
    And user "Carol" has created folder "/Carol-folder"                                                    # FeatureContext::userHasCreatedFolder()
    And user "Alice" has shared folder "/Alice-folder" with user "Brian" with permissions "all"            # FeatureContext::userHasSharedFileWithUserUsingTheSharingApi()
    And user "Carol" has shared folder "/Carol-folder" with user "Brian" with permissions "all"            # FeatureContext::userHasSharedFileWithUserUsingTheSharingApi()
    When user "Brian" moves folder "/Alice-folder/folder2" to "/Carol-folder/folder2" using the WebDAV API # FeatureContext::userMovesFileUsingTheAPI()
    And user "Carol" gets the info of the last share using the sharing API                                 # FeatureContext::userGetsInfoOfLastShareUsingTheSharingApi()
    Then the OCS status message should be "Only GET, POST and PUT are allowed"                             # OCSContext::theOCSStatusMessageShouldBe()
      Unexpected OCS status message :"OK" in response
      Failed asserting that two strings are equal.
      --- Expected
      +++ Actual
      @@ @@
      -'Only GET, POST and PUT are allowed'
      +'OK'
```
Actually this scenario is tagged `skipOnOcV10` so it is a special scenario for OCIS. Maybe it was a bug that is now fixed?

**Comment by phil-davis** [comment]
Related to https://github.com/owncloud/ocis-reva/issues/249

In theory we could delete scenario `apiShareUpdate/updateShare.feature:179` and remove `skipOnOcis` from `apiShareUpdate/updateShare.feature:147` - but 147 has other issues.

So I guess we need to adjust 179 so it does a bit more that now passes.

**Comment by PVince81** [comment]
I did touch the update share code and fixed some issues. So if a scenario needs to be adjusted in core let's do it right away.

**Comment by PVince81** [comment]
I actually meant to run all tests tagged with https://github.com/owncloud/ocis-reva/issues/252 but bumped into issues due to https://github.com/owncloud/ocis-reva/issues/249 which is also fixed (partly) in the current reva update, and got lost down the rabbit hole... I intend to look through all the tests related to these two tickets to see what we can enable.

**Comment by PVince81** [comment]
updated again to get https://github.com/cs3org/reva/commit/2f6cc60e2f66d8cc9f2312ee92551c4e9ee16c39

**Comment by phil-davis** [comment]
@PVince81 It should be good now if you update the core commit for tests https://github.com/owncloud/ocis-reva/blob/master/.drone.star#L4 to:
```
apiTests(ctx, 'master', 'a3cac3dad60348fc962d1d8743b202bc5f79596b'),
```
which is the new latest core master commit.

**Comment by phil-davis** [comment]
Now there is some problem with fetching composer PHP dependencies for behat...
```
composer bin behat install --no-progress
Loading composer repositories with package information
Updating dependencies (including require-dev)

                                                                            
  [Composer\Downloader\TransportException]                                  
  Content-Length mismatch, received 6975 bytes out of the expected 1860149  
                                                                            

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

Makefile:413: recipe for target 'vendor-bin/behat/vendor' failed
```
https://cloud.drone.io/owncloud/ocis-reva/572/2/6

The same has been happening to me in https://github.com/cs3org/reva/pull/927 e.g. https://cloud.drone.io/cs3org/reva/1692/4/6
I cannot get the composer dependencies to actually be fetched from packagist.

Some problem with packagist servers or cloud.drone.io network?

**Comment by PVince81** [comment]
Murphy's law

**Comment by phil-davis** [comment]
> Murphy's law

I restarted drone CI and Murphy is happy this time.

**Pull request merged**
