### PR TITLE
Update reva to v0.1.1-0.20200518061204

### PR DESCRIPTION
**Pull request by PVince81**

### CODE REVIEW

**Comment by PVince81** [comment]
Fixes https://github.com/owncloud/ocis-reva/issues/186
Fixes https://github.com/owncloud/ocis-reva/issues/203
Fixes https://github.com/owncloud/ocis-reva/issues/183

I've enabled the Litmus props tests, they should pass now!

**Comment by PVince81** [comment]
hmmm, a strange failure:
```

1) Scenario: without any share the shared-with-me page should be empty (attempt 2) # tests/acceptance/features/webUIFiles/fileDetails.feature:120
--
```

wondering if this is related to the Phoenix sidebar changes, but I don't see why it would fail with OCIS

**Comment by PVince81** [comment]
test is passing locally... attempting a build restart...

**Comment by PVince81** [comment]
okay, same failure. at least it's consistent...

```
Timed out while waiting for element <//nav[contains(@class, "oc-sidebar-nav")]/ul/li/a[contains(text(),"Shared with me")]> to be present for 20000 milliseconds. - expected "visible" but got: "not found" (20001ms)
```

**Comment by PVince81** [comment]
quick attempt: I've now set the screen resolution explicitly to 1920x1080, just in case.

to me it seems like maybe during that test on Drone the left sidebar is closed and the action for opening it might be missing

**Comment by PVince81** [comment]
hmm, I tested locally with 768x1024 but it still manages to open the sidebar, so it might be something else...

**Comment by PVince81** [comment]
the failure also exists on an other PR: https://cloud.drone.io/owncloud/ocis-reva/340/3/10

so it's not related to the update

**Comment by PVince81** [comment]
raised test PR https://github.com/owncloud/phoenix/pull/3471 to check if it was failing already on Phoenix master

**Comment by PVince81** [comment]
tests pass on Phoenix master: https://github.com/owncloud/phoenix/pull/3471 but not sure if it's 100% the same thing

@individual-it can you help ?

**Comment by individual-it** [comment]
It looks like we are not using the phoenix code from the phoenix repo but the code that is compiled into ocis, so we don't get the current phoenix. that is a mistake, @dpakach please fix that

**Comment by dpakach** [comment]
@PVince81  The phoenix version should be fixed by https://github.com/owncloud/ocis-reva/pull/209
Please rebase after that gets merged.

**Comment by PVince81** [comment]
Rebased and removed the forced screen resolution which did not solve the issue anyway

**Pull request merged**
